### ISSUE TITLE
Having the SuperUnityBuild editor window open in the inspector causes noticeable lag in play mode

### ISSUE THREAD

**Issue by XaeroDegreaz** [Chaser324/unity-build#14]
It seems to only happen when the window is active -- if it's part of a tab group and not activated there's no lag. It doesn't appear to affect the actual framerate (according to the stats dropdown) but it seems to cause a bit of UI lag. Feels like every .25 seconds or something.

It seems to lag not only the play window, but other UI responsiveness such as editing text fields.

**Comment by Chaser324** [comment]
Thanks for pointing this out. I do typically keep it in a tab that's only active when I'm using it, so I guess I haven't noticed.

I suspect this is probably caused by the window repainting more often than is necessary. That would explain why it only happens when you have it visible and active. It also makes sense that it would be that because I know my code related to that is a bit sloppy. I was having trouble making sure that undo/redo events were caught and reflected in the UI, so I probably overcompensated in dealing with that issue.

**Comment by XaeroDegreaz** [comment]
Gotta love `OnGUI`.

I had the same issue that I never really could overcome for an in-Unity Git client I put on the asset store a few years back.

**Comment by Chaser324** [comment]
It is a tough problem to tackle. I'm sure there's probably a better solution than whatever I'm doing now, but it wasn't immediately apparent at the time I was initially setting up things. I'll take another look and see what I can do to improve things.

**Comment by Chaser324** [comment]
I just pushed a commit that should help with this. For me, Unity was using about 5% CPU while idling with the Unity Build window open, and now it's idling at less than 1% CPU. Take a look and let me know if you think it's sufficient.

**Comment by Chaser324** [comment]
Going to go ahead and close this for now. While I'm sure more improvements can be made, I haven't heard any complaints in a while.
