### ISSUE TITLE
Continuous Error

### ISSUE THREAD

**Issue by Modelmat** [Chaser324/unity-build#21]
I continuously get this error Unity 207.1

```Assets/UnityBuild/Editor/Build/Settings/UI/ProjectConfigurationsDrawer.cs(177,53): warning CS0618: `UnityEditor.EditorUserBuildSettings.SwitchActiveBuildTarget(UnityEditor.BuildTarget)' is obsolete: `Please use SwitchActiveBuildTarget (BuildTargetGroup targetGroup, BuildTarget target)'```

**Comment by Chaser324** [comment]
Thanks for letting me know. I haven't taken the dive into 2017 yet, but I'll grab it today and fix this.

**Comment by Chaser324** [comment]
Hmm...now that I'm looking at this, I'm not actually getting this warning. This function was changed in Unity 5.6, and I'm already accounting for that:

```csharp
#if UNITY_5_6_OR_NEWER
    EditorUserBuildSettings.SwitchActiveBuildTarget(platform.targetGroup, arch.target);
#else
    EditorUserBuildSettings.SwitchActiveBuildTarget(arch.target);
#endif
```

If you're running Unity 2017.1, I'm not sure why it would be trying to run the old deprecated function. I'm testing this in Unity 2017.1.1f1, and I'm getting the expected behavior.

If the platform dependent compilation is not working for you, I'm leading towards that actually being a bug in Unity itself.

**Comment by Chaser324** [comment]
Ah, I just realized that I did not do an updated .unitypackage release with that fix, so that's probably the issue.

I have now remedied that issue and you can get the most up to date package here: https://github.com/Chaser324/unity-build/releases/tag/v0.9.5
