### ISSUE TITLE
Does not build to Linux x64

### ISSUE THREAD

**Issue by viperp12** [Chaser324/unity-build#39]
No matter what is checked, it always builds to Linux x86. Universal is being depreciated.

**Comment by rthery** [comment]
It builds x64 fine, the problem is the binaries file name, it doesn't take into consideration CPU architecture, and default to x86 for Linux builds. I just submitted a PR resolving this.

**Comment by malkere** [comment]
So renaming the filename to x86_64 would solve this temporarily?

**Comment by rthery** [comment]
Yes, the problem is just the filename doesn't depend on the architecture. If you check my PR and that change specifically https://github.com/Chaser324/unity-build/pull/41/commits/d27794ab888eef5c5ce86690e76ef4de3e068758#diff-a7c51b91f13c4484889631587e54aafc you'll see that all architectures are supported, but the binary name format is always "{0}.x86"

**Comment by malkere** [comment]
I just set a post build operation to change the file name for now.

**Comment by TupiNUMBooR** [comment]
Will it be resolved?
